#
# Module manifest for module 'azdo-dsc-lcm'
#
# Generated by: Michael Zanatta
#
# Generated on: 10/10/2024
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'azdo-dsc-lcm.psm1'

    # Version number of this module.
    ModuleVersion = '0.1'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID = '1e4519dc-19e4-4cb2-a5e8-83d571a4d1ca'

    # Author of this module
    Author = 'Michael Zanatta'

    # Company or vendor of this module
    CompanyName = 'Akkodis 2024'

    # Copyright statement for this module
    Copyright = '© Akkodis 2024. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Local Configuration Manager (LCM) for Azure DevOps'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # Not applicable: this module requires PowerShell 7.0 / PSEdition Core.
    # ClrVersion = '4.0'

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        @{
            ModuleName = 'PSDesiredStateConfiguration'
            ModuleVersion = '2.0.0'
        }
        @{
            ModuleName = 'powershell-yaml'
            MaximumVersion = '1.0.0'
        }
        @{
            ModuleName = 'AzureDevOpsDsc.Common'
            MaximumVersion = '1.0.0'
        }
        @{
            ModuleName = 'AzureDevOpsDsc'
            MaximumVersion = '1.0.0'
        }
        @{
            ModuleName = 'datum'
            MaximumVersion = '1.0.0'
        }
        @{
            ModuleName = 'Datum.InvokeCommand'
            MaximumVersion = '1.0.0'
        }
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    # These are script functions, not compiled cmdlets, so they must be declared here rather than in CmdletsToExport.
    FunctionsToExport = @(
        'Build-DatumConfiguration'
        'Invoke-AZDoLCM'
        'Resolve-AzDoDatumProject'
        'Stop-TaskProcessing'
        'Test-DatumConfiguration'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module. The module-scope $references, $variables and $parameters
    # hashtables are internal LCM state and must not be published into the caller's session.
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData        = @{

        PSData = @{
            # Set to a prerelease string value if the release should be a prerelease.
            Prerelease   = ''

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/ZanattaMichael/AzDO-DSC-LCM/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/ZanattaMichael/AzDO-DSC-LCM'

            # A URL to an icon representing this module. Must be a raw content URL to resolve to the image itself.
            IconUri      = 'https://raw.githubusercontent.com/ZanattaMichael/AzDO-DSC-LCM/main/icon.png'

            # ReleaseNotes of this module. Populated from CHANGELOG.md by the Sampler release pipeline.
            ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

