#
# Module manifest for module 'Dsc.PipelineRunner'
#
# Generated by: Michael Zanatta
#
# Generated on: 10/10/2024
#

@{

    Path = "./Dsc.PipelineRunner.psd1"
    ModuleManifest = "./Dsc.PipelineRunner.psd1"
    # Script module or binary module file associated with this manifest.

}

